import 'dart:typed_data';

import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../../data/models/exam.dart';
import '../../data/models/inference_result.dart';

/// Builds a printable OXALIA analysis PDF from exam + inference data.
class ReportPdfBuilder {
  ReportPdfBuilder._();

  static Future<Uint8List> build({
    required Exam exam,
    required InferenceResult result,
  }) async {
    final sorted = [...result.findings]
      ..sort((a, b) => b.probability.compareTo(a.probability));
    final top = sorted.isNotEmpty ? sorted.first : null;

    final doc = pw.Document();
    doc.addPage(
      pw.MultiPage(
        pageFormat: PdfPageFormat.a4,
        margin: const pw.EdgeInsets.all(40),
        build: (context) => [
          pw.Text(
            'OXALIA 2D — Analysis Report',
            style: pw.TextStyle(fontSize: 22, fontWeight: pw.FontWeight.bold),
          ),
          pw.SizedBox(height: 8),
          pw.Text(
            'AI-assisted analysis — Not a clinical diagnosis.',
            style: const pw.TextStyle(fontSize: 10, color: PdfColors.grey700),
          ),
          pw.SizedBox(height: 24),
          _metaRow('Exam ID', exam.id),
          _metaRow('File', exam.originalFilename),
          _metaRow('Date', exam.createdAt.toLocal().toIso8601String()),
          _metaRow('Model', result.modelVersion),
          _metaRow('Status', exam.status.name),
          pw.SizedBox(height: 20),
          pw.Text(
            'PREDICTION',
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey600,
            ),
          ),
          pw.SizedBox(height: 6),
          pw.Text(
            top?.label ?? 'No findings',
            style: pw.TextStyle(fontSize: 18, fontWeight: pw.FontWeight.bold),
          ),
          if (top != null) ...[
            pw.SizedBox(height: 4),
            pw.Text(
              'Confidence: ${(top.probability * 100).toStringAsFixed(1)}%',
              style: const pw.TextStyle(fontSize: 12),
            ),
          ],
          pw.SizedBox(height: 20),
          pw.Text(
            'DETECTED FINDINGS',
            style: pw.TextStyle(
              fontSize: 11,
              fontWeight: pw.FontWeight.bold,
              color: PdfColors.grey600,
            ),
          ),
          pw.SizedBox(height: 8),
          for (final f in sorted)
            pw.Padding(
              padding: const pw.EdgeInsets.only(bottom: 4),
              child: pw.Row(
                mainAxisAlignment: pw.MainAxisAlignment.spaceBetween,
                children: [
                  pw.Text(f.label, style: const pw.TextStyle(fontSize: 11)),
                  pw.Text(
                    '${(f.probability * 100).toStringAsFixed(1)}%',
                    style: const pw.TextStyle(fontSize: 11),
                  ),
                ],
              ),
            ),
          pw.SizedBox(height: 32),
          pw.Text(
            'This report is generated by OXALIA 2D for clinical decision support '
            'only. Final diagnosis remains the responsibility of a licensed clinician.',
            style: const pw.TextStyle(fontSize: 9, color: PdfColors.grey600),
          ),
        ],
      ),
    );

    return doc.save();
  }

  static pw.Widget _metaRow(String label, String value) {
    return pw.Padding(
      padding: const pw.EdgeInsets.only(bottom: 4),
      child: pw.Row(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.SizedBox(
            width: 90,
            child: pw.Text(
              label,
              style: const pw.TextStyle(fontSize: 11, color: PdfColors.grey600),
            ),
          ),
          pw.Expanded(
            child: pw.Text(value, style: const pw.TextStyle(fontSize: 11)),
          ),
        ],
      ),
    );
  }
}
